export const INTEREST_STATUS = {
  ALL: "all",
  INTERESTED: "Interested/Engaged",
  NEGOTIATING: "Negotiating",
  DO_NOT_CONTACT: "Do Not Call",
  CLOSED: "Closed",
  FOLLOW_UP: "Follow Up",
  NOT_INTERESTED: "Not Interested",
  NO_RESPONSE: "No Response",
  NURTURE: "Nurture",
  UNKNOWN: "Unknown",
};

export const INTEREST_STATUSES = [
  INTEREST_STATUS.INTERESTED,
  INTEREST_STATUS.NEGOTIATING,
  INTEREST_STATUS.DO_NOT_CONTACT,
  INTEREST_STATUS.CLOSED,
  INTEREST_STATUS.FOLLOW_UP,
  INTEREST_STATUS.NOT_INTERESTED,
  INTEREST_STATUS.NO_RESPONSE,
  INTEREST_STATUS.NURTURE,
  INTEREST_STATUS.UNKNOWN,
];
