export const prospectListTemplate = [
  {
    firstName: 'First Name',
    lastName: 'Last Name',
    address1: 'Street Address',
    address2: 'Apartment',
    city: 'City',
    state: 'State',
    zip: 'Zip',
    company: 'Company',
    phone: '(555) 555-555',
    email: 'email',
    facebook: 'facebook',
    status: 'Interested'
  },
  {
    firstName: 'First Name',
    lastName: 'Last Name',
    address1: 'Street Address',
    address2: 'Apartment',
    city: 'City',
    state: 'State',
    zip: 'Zip',
    company: 'Company',
    phone: '(555) 555-555',
    email: 'email',
    facebook: 'facebook',
    status: 'Interested'
  },
  {
    firstName: 'First Name',
    lastName: 'Last Name',
    address1: 'Street Address',
    address2: 'Apartment',
    city: 'City',
    state: 'State',
    zip: 'Zip',
    company: 'Company',
    phone: '(555) 555-555',
    email: 'email',
    facebook: 'facebook',
    status: 'Interested'
  },
  {
    firstName: 'First Name',
    lastName: 'Last Name',
    address1: 'Street Address',
    address2: 'Apartment',
    city: 'City',
    state: 'State',
    zip: 'Zip',
    company: 'Company',
    phone: '(555) 555-555',
    email: 'email',
    facebook: 'facebook',
    status: 'Interested'
  },
  {
    firstName: 'First Name',
    lastName: 'Last Name',
    address1: 'Street Address',
    address2: 'Apartment',
    city: 'City',
    state: 'State',
    zip: 'Zip',
    company: 'Company',
    phone: '(555) 555-555',
    email: 'email',
    facebook: 'facebook',
    status: 'Interested'
  },
]