export const ACTIONS = {
  SET_USER: 'SET_USER',
  SET_PROSPECTS: 'SET_PROSPECTS',
  SET_PROSPECT_LIST: 'SET_PROSPECT_LIST',
  SET_SINGUP_STEP: 'SET_SINGUP_STEP',

  UPDATE_CREATE_CAMPAIGN: 'UPDATE_CREATE_CAMPAIGN',

  SET_COMPLETED_PROSPECT_LIST_ID: 'SET_COMPLETED_PROSPECT_LIST_ID',
};

export const CREATE_CAMPAIGN_ACTIONS = {
  INIT: 'INIT',

  UPDATE_STEP: 'UPDATE_STEP',
  UPDATE_SUBSTEP: 'UPDATE_SUBSTEP',
  UPDATE_DEFAULT_PROSPECTS: 'UPDATE_DEFAULT_PROSPECTS',

  UPDATE_DETAILS: 'UPDATE_DETAILS',
  UPDATE_OUTREACH_EMAIL: 'UPDATE_OUTREACH_EMAIL',
  UPDATE_OUTREACH_TEXT: 'UPDATE_OUTREACH_TEXT',
  UPDATE_OUTREACH_RINGLESS_VOICEMAIL: 'UPDATE_OUTREACH_RINGLESS_VOICEMAIL',
  UPDATE_OUTREACH_POST_CARD: 'UPDATE_OUTREACH_POST_CARD',
  UPDATE_OUTREACH_SOCIAL_POST: 'UPDATE_OUTREACH_SOCIAL_POST',
  UPDATE_TIMELINE: 'UPDATE_TIMELINE',
  UPDATE_CHECKOUT: 'UPDATE_CHECKOUT',
};

export const UPLOAD_STATUS = {
  STARTED: 'started',
  UPLOADED_ONE: 'uploaded one item',
  COMPLETED_UPLOAD: 'completed to upload',
  ERROR: 'error occured',
};
